
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1358406
	#The name of the modpack
	modpackName = "Deicide - Fractured Divinity (lite)"
	#The version of the modpack
	modpackVersion = "0.1.6"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

