
[Mobs]
	#Example: ["minecraft:zombie", "minecraft:skeleton"]
	"List of mobs that shouldn't be able to level up" = []
	#If this list is not empty only these mobs will be able to level up
	#Example: ["minecraft:zombie", "minecraft:skeleton"]
	"List of mobs that should be able to level up" = ["galosphere:berserker", "legendary_monsters:skeletosaurus", "legendary_monsters:warped_fungussus", "legendary_monsters:lava_eater", "legendary_monsters:withered_abomination", "legendary_monsters:ancient_guardian", "minecraft:elder_guardian", "legendary_monsters:posessed_paladin", "mowziesmobs:ferrous_wroughtnaut", "dungeonnowloading:chaos_spawner", "soulsweapons:draugr_boss", "soulsweapons:night_shade", "bosses_of_mass_destruction:void_blossom", "irons_spellbooks:dead_king", "block_factorys_bosses:yeti", "legendary_monsters:frostbitten_golem", "legendary_monsters:overgrown_colossus", "aquamirae:captain_cornelia", "mowziesmobs:umvuthi", "bosses_of_mass_destruction:lich", "born_in_chaos_v1:lord_pumpkinhead", "soulsweapons:accursed_lord_boss", "hadean_breathe:hadean_enforcer", "graveyard:lich", "legendary_monsters:cloud_golem", "block_factorys_bosses:infernal_dragon", "soulsweapons:returning_knight", "block_factorys_bosses:underworld_knight", "block_factorys_bosses:sandworm", "mowziesmobs:frostmaw", "bosses_of_mass_destruction:gauntlet", "dungeonnowloading:fairkeeper_boros", "dungeonnowloading:fairkeeper_ouros", "goety:vizier", "alexscaves:luxtructosaurus", "minecraft:wither", "minecraft:ender_dragon", "bosses_of_mass_destruction:obsidilith", "mofus_better_end_:endermite_queen", "mofus_better_end_:eye_guardian", "mofus_better_end_:forgotten_litch", "mofus_better_end_:reborn_litch", "alexsmobs:void_worm", "cataclysm:netherite_monstrosity", "soulsweapons:chaos_monarch", "legendary_monsters:endersent", "legendary_monsters:shulker_mimic", "cataclysm:ender_guardian", "cataclysm:the_harbinger", "cataclysm:ancient_remnant", "soulsweapons:moonknight", "goety:apostle", "soulsweapons:day_stalker", "soulsweapons:night_prowler", "cataclysm:maledictus", "cataclysm:the_leviathan", "cataclysm:scylla", "cataclysm:ignis", "traveloptics:the_nightwarden", "macabre:baal", "macabre:gomoria", "macabre:valamon", "macabre:gargamaw", "macabre:morphegor", "darkdoppelganger:dark_doppelganger", "minecraft:warden"]
	"Always show mobs levels" = false
	"Only show levels when you look at the mob" = true
	"Bonus experience per level" = 0.1
	"List of mobs that should have their levels always hidden" = []

[Attributes]
	#Contains a list of pairs of attributes and their bonuses per one level
	"Attributes bonuses per one level" = [["minecraft:generic.movement_speed", 0.001], ["minecraft:generic.flying_speed", 0.001], ["minecraft:generic.attack_damage", 0.1], ["minecraft:generic.armor", 0.1], ["minecraft:generic.max_health", 0.1], ["autoleveling:monster.projectile_damage_bonus", 0.1], ["autoleveling:monster.explosion_damage_bonus", 0.1]]

["Default levelling settings"]
	"Starting level" = 1
	#If this is equal to 0, there will be no maximum level
	"Maximum level" = 0
	"Level increase per one block distance from spawn" = 0.01
	"Level increase per one block deepness below sea level" = 0.005
	#If this is higher than 0, the level of monsters will be randomly increased by value between 0 and this value
	"Random level bonus" = 5
	#If this is higher than 0, mobs level will increase every day by specified amount
	"Level bonus per day" = 0.0
	#Exponential level increase with distance
	level_power_per_distance = 0.0
	#Exponential level increase with deepness
	level_power_per_deepness = 0.0

